# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Survey CI

on:
  push:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Running Build Check for all Survey
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version: [20.11]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.11
      uses: actions/setup-node@v4
      with:
        node-version: 20.11
        cache-dependency-path: src/**/package-lock.json
        cache: 'npm'
    - name: Build
      run: |

        chmod +x ./build.sh && ./build.sh  
      working-directory: src/
  
  publish:
    name: Package & publish Survey
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.11
      uses: actions/setup-node@v4
      with:
        node-version: 20.11
        cache-dependency-path: src/**/package-lock.json
        cache: 'npm'
    - name: Build
      run: |
        chmod +x ./build.sh && ./build.sh
      working-directory: src/

    - name: Publish
      run: |
        chmod +x ./publish.sh && ./publish.sh
      working-directory: src/

    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # Upload entire repository
        path: './src/build/'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
  

  
